site_name: linko的小站
site_url: https://rinko224.github.io/
site_author: linko
theme:
  name: material
  favicon: image/R.jpg
  logo: image/R.jpg
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
nav:
  - 首页: index.md
  - 数学: 
    - 解题笔记: 数学/questions.md
    - 随笔: 
       - quine.md
       - a function equation.md
  - 计算机系统: 
    - 说明: 计算机系统/index.md
    - 对象存储控制器关键技术研究: 计算机系统/对象存储控制器关键技术研究.md
  - 机器学习/人工智能: 机器学习、人工智能/ml.md
  - 项目: 
    - PokemonVs: 项目/pokemonvs.md

repo_url: https://github.com/rinko224/rinko224.github.io
repo_name: rinko224
